---
  #- src: git@github.com:netology-code/mnt-homeworks-ansible.git
  - src: git@github.com:kaa-ansible/mnt-homeworks-ansible.git
  #https://github.com/kaa-jenkins/mnt-homeworks-ansible.git
    #git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "1.0.1"
    name: java 
    key_file: ./secret
