pipeline {
    agent {
        label "ansible_docker"
    }

    stages {
        stage('prepare_node') {
            steps {
                git 'https://github.com/kaa-jenkins/example-playbook.git'
                sh 'ansible-vault decrypt secret --vault-password-file vault_pass'
                
                ##ключ с именеи id_rsa будет использоваться по умолчанию
                sh 'mkdir -p ~/.ssh/ && mv ./secret ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa'
                
                #http://debuggable.com/posts/disable-strict-host-checking-for-git-clone:49896ff3-0ac0-4263-9703-1eae4834cda3
		#This will add a configuration line to your ~/.ssh/config script that will silently ignore the authenticity of github.com.
                sh 'echo -e "Host github.com\\n   StrictHostKeyChecking no\\n   UserKnownHostsFile=/dev/null" > ~/.ssh/config'
                
                
                #Если ключ имеет другное имя, то определить его можно так:
		#mv ./secret ~/.ssh/rsa	
		#eval "$(ssh-agent -s)"
		#ssh-add ~/.ssh/rsa

		#Установка зависимостей и запуск ansible
                sh '''ansible-galaxy install -r requirements.yml -p roles
                ansible-playbook site.yml -i inventory/prod.yml'''
            }
        }
    }
}